var level_1 = [
    '#################################################################################                ',
    '#             #                   #               #                             #                ',
    '#             #                   # o           o #                             #                ',
    '#             # o                 ###     o     ###     o       o               #                ',
    '#              #                     ##       ##                                #                ',
    '#               ######                                  ##  o  ##               #                ',
    '#  o                      E             #####                                   #                ',
    '#           #             ######       ## o ##            E              o o    #                ',
    '#  #       ##            ## o  #      ### o ###        ############      o o    #                ',
    '# ###     ###E          ### o        ###     ###       #         H#             #                ',
    '########################################  ___###########          ###########   #                ',
    '#                                      #                       ##############   #                ',
    '#                                      #                  #######               #                ',
    '#      o                    o          ##   ##############                  #####                ',
    '#                           o                          o                   #    #   #######      ',
    '#    #####       oo                      E                      o         #     #  #       #     ',
    '#o     ####o             o     o       ##########                        #      ###         ###  ',
    '###    #####     ##     ###   ###                    E         ###    ###       ###           #  ',
    '#   o  ######    ##     ##     ##          o         ######                      #            #  ',
    '#      ######vvvv##vvvvv##vvvvv##     ############                           o   L     P      #  ',   
    '###   #########################################################################################  ',
    '#     #####################                                                              ######  ',
    '#     ###############                                                                    ######  ',
    '#   ###########                                                                          ######  ', 
    '#                                                                                        ######  ',
    '#                                                o                                       ######  ',   
    '###                                            E            oo                           ######  ',   
    '####       o         o                         ######      ####          o  o      K     ######  ',   
    '#####                       ####        ####              ########                       ######  ',   
    '######                     #####E     ######            ##########E     ######           ######  ',   
    '###############################################################################################  ', 
    '###############################################################################################  ',    
 ];
 
 var level_2 = [
    '#                                                                                  ###################',
    '#                                                                                  #                 #',
    '#                                                   ooo                            #                 #',
    '#           o         o                          #########                         #               K #',
    '#                                      o        #        #            #            #          o    ###',
    '#    o    #####      ###     ###       o      ##         #         #######       o # o               #',
    '#           #         #       #       ###     #    o     #           >#<           L         ___     #',
    '#   ###     #         #       #vvvvvvvvvvvvvvv#   ooo    #           >#<        ___#___    vvvvvvvvvv#',
    '#    #      #         #      ##################    o     ######   o  >#<  o        #       ###########',
    '#vvvv#vvvvvv#vvvvvvvvv#vvvvvv#                                L      >#<           #                 #',
    '############################## ################################################    #____             #',
    '#                              #                                            ###    #                 #',
    '# K    o      o       o     K  # o                                          ##    #       o          #',   
    '###################################                                         #    #       ___         #', 
    '#                              #                            o  o  o  o  o   #    #                   #', 
    '#                              #     E                                      #    #      ######       #', 
    '#    P                         #     ______               E        #E       #    #      #            #', 
    '###########                    #                    ###  ####################  __#______#          __#', 
    '############                   #                   ####                     #S          #    K       #', 
    '#############                  L         #E       #####                     L           #vvv###vvvvvv#',    
    '######################################################################################################',   
 ];
 
 var level_3 = [
    '#                                                                                                    ###############################################################',
    '#                                                                                                   K#                                                       #     #',
    '#                                                                                         TTT        #                                                       #     #',
    '#                                                o   o    oo                   o o                   #                                                       #     #',
    '#S                                               #vvv#    __    E             _____                  #                                                       #     #',
    '#                   o      oo       o            #####         #######                               #                                                       #     #',
    '#                  ##      ##       ##     o  o    #                                                 #           o     o     o                               #     #',
    '#         ####                             ####    #vvvvvvvvvvvvvvvvvv                               #    ##<   >#<    o    >#<   ##         o               #     #',
    '#        #####                                     ###################   ##                          #   ###<   >#<   >#<   >#<   ###        v               #     #',
    '#       ######vvvvvvvvvvvvvvvvvvvvv vvvvvvvvvvvvvvv#             #   L   ##                          L  ####vvvvv#vvvvv#vvvvv#vvvv####E     >#<E             L  P  #',
    '################################### ##############################  ###################################################################################o  ##########', 
    '###################################  K o   o   o   o   o   o   o H  #                                                                                 #   #        #',
    '#                                  _________________________________                                                                                  #   #        #',   
    '#                                                                                                                                                     #_  #        #',
    '#                                                                                                                                                     #   #        #',
    '#             o o o                                                                                                   o    vv    o                    #  o#        #',   
    '#S                                                      o    oo     o                  o K o                         #### >##< ####S                  #  _#        #',   
    '#  ooo       #######S                                 >##<  >##<  >##<               #########                 oo         >##<         oo                          #',
    '#  oHo      #########          #     #    #            ^^    ^^    ^^               #         #               ___#         ^^         #___              o          #', 
    '#  ooo     ###########        ##vvvvv#vvvv#E     #vvvvvvvvvvvvvvvvvvvvvvvv#        #           #                 #vvvvvvvvvvvvvvvvvvvv#              #######       #',  
    '####################################################################################################################################################################',    
 ];
 
 var level_4 = [
    'T                                         K     TT     TT        TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT        TT                    TTTTTTTTT            T',
    'T                o o o o                                          T                                        >T<      >TTH  S    o o        TTTTTT                T',
    'T                TTTTTTT                                          T                           o o           T       >TT_      _____       TTTTTT                T',
    'T                                                                 T                                         Lo      >TT                   TTTTTT                T',
    'T                             TTT                                 T K                                      _T__      TT              __   TTTTTT                T',
    'T                                        o  o       E             TTTTTT    TT     TTT       TTTTT          T<       TT                   TTTTTT                T',
    'T   oo                    o o                       TTTTT         T                         TTTTTTT      oooT<       TT                   TTTTTT                T',
    'T   TT                    TTT            TTTT                     T                                      TTTTH       TTTTTTTTTTTTTTTTTTTT TTTTTT                T',
    'T                                                                 T                                         T__    S                      TTTTTT        K       T',                    
    'TvvvvvvvvTTTTTTTTTvvvTTvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvT       TTTTTTTTTTTTTTTTTTTTTTTT             TvvvvvvTTTTT  TTTTTTTTTTT  TTTTTTTTT       TTT      T',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT H o o o o            TTvvvvvvvvvvvvTTTTTTTTTTTTTTT  L   o o o o o o o L    TTTTTTTTTT  T', 
    'T  T    T                                                              TTTTTTTTTTTTTTTTTTTTT  TTTTTTTTTTTTTTTTTTTTTTTTTTTT   TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT_ T',  
    'TH L    T                                                                                                                   T                                   T',  	
    'TTTTT                                                                                TT    oooo                            TT                                   T',   	
    'T    TT                                                                                   _TTTT_                   TTTTTTTTT            _                      _T',  
    'T                                                     ____                _______                               S TTT                          _                T',  
    'T P                      ___          >#<                                                                        TTSK                    ooS         oo         T',  
    'TTTTTTTTTTTTTTTTTTTS           ____    ^    ____           ____                                                 TTT _________      _     __          __      ___T',  
    'T                                                                    TTTTTTTTTTTTTTTTS    ______      __       TTTT          _                                  T',  
    'TvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvTTTTTTvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvT', 
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',   	
 ];
 
 var town = [
    '#                                                                                                                                                                  #',
    '#                                                                                                                                                                  #',
    '#                                                                                                                                                                  #',
    '#                                                                                                                                                                  #',
    '#                                                                                                                                                                  #',
    '#                                                                                                                                                                  #',
    '#                                                                                                                                                                  #',
    '#                                                                                                                                                                  #',
    '#                                                                                                                                                                  #',
    '####################################################################################################################################################################', 
    '####################################################################################################################################################################',    
 ];

 var levels = [level_1, level_2, level_3, level_4];