var level_1 = [
    '#################################################################################          ###^^^^^^^^^^^^    #',
    '#             #                   #               #                             #          #oovvvvvvvvvvvv    #',
    '#             #                   #o             o#                             #          #o#############    #',
    '#        o o #                     ##     o     ##                              #          #o #S            oo#',
    '#       #####                                                                   #          #o #             ~ #',
    '# o                                                      o      o               #          #ooo#          S   #',
    '#                         E             #####            ~     ~                #          #oooo#             #',
    '#___                      ######       ## o ##                                  #          #ooooo##    ~      #',
    '#                #       ## o         ### o ###           E                   o #           oooooo###<     S  #',
    '#               ##E     ### o        ####   ####       ############             #          ###########<   ~  >#',
    '########################################__   ###########         H###########   #                     #      >#',
    '#                                                              ####             #                      #    oo#',
    '#                                         ~ ####################                #                      #    ~ #',
    '#      o                                                                        #      D               #E     #',
    '#                                                                          ######   ##~ ~##            #~ ~ ~ #',
    '#      ###        o              o       E                      o         #     #  #       #           #      #',
    '#      ####              oo              ______                       ####      ###         #          #  S   #',
    '#    __#####      ~      __      ~                             ___              ###         #          #~     #',
    '# o    ######                              o         E                           #          #          #    oo#',
    '#      ######vvvvvvvvvvvvvvvvvvvvvvvvv############vvv######                  o   L     P   M#          #    ~ #',   
    '#__   #######################################################################################          #      #',
    '#     ####                                                                                             #E     #',
    '#   __##                                                                                               #~ ~ ~ #',
    '#                                                                      K                 ######      ###      #', 
    '#                                                                                        ######      ##      S#',
    '#__                                                                    ~       oo        ######      #      ~ #',   
    '#                                               E                              ~         ######      #  S     #',   
    '#          o         o      E                   ______                                 ~ ######oo        ~    #',   
    '###        ~        ~     _########_    ####              #####                          ######~   o o        #',   
    '########vvvvvvvvvvvvvvvvvvvv######vvvvvv####vvvvvvvvvvvv########                         ###### o o H o       #',   
    '#########################################################################################################vvvvv#', 
    '###############################################################################################################',    
 ];
 
 var level_2 = [
    '#                                                                                  ###################                  #',
    '#                                                                                  #                 #                  #',
    '#                                                   o o                            #                 #                  #',
    '#           o         o                          #########                         #               K #                  #',
    '#                                      o        #        #            #            #          o    ###                  #',
    '#    o   #######     ###     ###       o      ##         #         #######       o # o       ___     #                  #',
    '#           #         #       #       ###     #          #           >#<           L       vvvvvvvvvv#                  #',
    '#   ###     #         #       #vvvvvvvvvvvvvvv#   o o o  #           >#<        ___#___    ###########                  #',
    '#    #      #         #      ##################          ######   o  >#<  o        #                                    #',
    '#vvvv#vvvvvv#vvvvvvvvv#vvvvvv#                                L      >#<           #                                    #',
    '############################## ################################################    #____             #___               #',
    '#                              #                                            ###    #     o  o        #                  #',
    '# k    o      o       o     K  #ooo                                         ##    #      ____        #        __        #',   
    '###################################                                         #    #                   #                  #', 
    '#     #                        #                            o  o  o  o  o   #    #                   #              #####', 
    '#     #                        #     E                                      #    #      ######       #             #    #', 
    '# D   l  M                     #     ______               E        #E       #    #      #            #             #    #', 
    '#___########                   #                    ###  ####################  __#______#          __#           __#    #', 
    '#   #########                  #                   ####                     #S          #    K       #             #    #', 
    '# __##########    P            L         #E       #####                     l           #vvv###vvvvvv#         Y   l    #',    
    '#   ################################################################################################################    #',
    '#                                                                                              #                        #',
    '#__                                                                                            #                      __#',
    '#                                                                                              #                        #',
    '#    k                                                                                         #                        #',
    '#######     H o o o o o o o o H                                                                #                        #',
    '#################################################### o  o                                      #           R            #',
    '                                                    ###### o      o                            #           ~            #',
    '                                                          ########## o   o                     #                        #',
    '                                                                   ########  o o o o           l                        #',
    '                                                                   ######################################################', 
 ];
 
 var level_3 = [
    '#                                                                                                    ###############################################################                                                ',
    '#                                                                                                   K#                                                       #     #                                                ',
    '#                                                                                        TTT         #                                                       #     #                                                ',
    '#                                                o   o    oo                   o o                   #                                                       #     #                                                ',
    '#S                                               #vvv#    __   E              _____                  #                                                       #     #                                                ',
    '#                   o      oo       o            #####         ######                                #                                                       #     #                                                ',
    '#                  ##      ##       ##     o  o    #                                                 #           o     o     o                               #     #                                                ',
    '#         ####                             ####    #vvvvvvvvvvvvvvvvvv   ##                          #    ##<   >#<    o    >#<   ##         o               #     #                                                ',
    '#        #####                                     ###################   ##                          #   ###<   >#<   >#<   >#<   ###        v               #     #                                                ',
    '#       ######vvvvvvvvvvvvvvvvvvvvv vvvvvvvvvvvvvvv#             #   L  ####                         L  ####vvvvv#vvvvv#vvvvv#vvvv####E     >#<E             L  P  #                                                ',
    '################################### ##############################  ###################################################################################o  ##########                                                ', 
    '###################################  K o   o   o   o   o   o   o H  #                                                                                 #   #        #                                                ',
    '#                                  _________________________________                                                                                  #   #        #                                                ',   
    '#                                                                                                                                                     #_  #        #                                                ',
    '#             o o o                                                                                                        vv                         #   #        #                                                ',
    '#             o H o                                                                                                   oo  >##<  oo                    #  o#        #                                                ',   
    '#S            o o o                                     o    oo     o                  o K o                         #### >##< ####S                  #  _#        #       oo                                       ',   
    '######        ##### S                                 >##<  >##<  >##<               #########                  o          ^^          o                           #       TT       TTTT                            ',
    '#    #       #######           #     #    #            ^^    ^^    ^^               #         #                 ##vvvvvvvvvvvvvvvvvvvv##                o          ##vvvvvvvvvvvvvvvvvvvv                           ', 
    '#  D l   M  #########         ##vvvvv#vvvv#E     #vvvvvvvvvvvvvvvvvvvvvvvv#        #           #              ##############################################################################~                       ',  
    '#____##########################################################################################################                                                                          T                          ',    
    '#                                                                                                                                                  T                                     T                          ',
    '#                                                                                                                                                  T                                     T                          ',
    '#____                                                                                                                              oo              T           S                 S       T                          ',
    '#                                    o                            k                   S                                            TT     oo       T                     S              kT                          ',
    '#                                    T       o       S            T            o                                          o               TT       T       ~        ~        ~         ~ T                          ',
    '#____                                        T              T        S         T        T                          S     TTT                  S   TT                                    ST                          ',
    '#                                                    o                                                                   TTT                       T  ~   S                              T                          ',
    '#                                                    T                                          T             S          TTT        S      TT      T                      S              T                   H      ',
    '#____            oooo                                       oo      oo                                         oo                                  l      ~                                     STT#S        TTTTTTT',
    '#         TT     TTTT                                       TT      TT                              TTTS       TT                                 TTT         ~       ~ S      ~       TTTTTTTTTTTT#         T     T',
    '#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    '####################################################################################################################################################################################################################',   
 ];
 
 var level_4 = [
    'T                                                     k           TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT        TT                     TTTT                T',
    'T                o o o o                                          T                                         T<      >TT       o S o       oTTTTT                T',
    'T                TTTTTTT                                          T                           o o           T       >TT       _____       TTTTTT                T',
    'T                                                                 T                                         Lo      >TT                   TTTTTT                T',
    'T                             TTT                                 T K                                      _T__      TT              __   TTTTTT                T',
    'T                                        o  o                     TTTTTT    TT     TTT       TTTTT          T<       TT                   TTTTTT                T',
    'T   oo                    o o                      E              T                         TTTTTTT      oooT<       TT                   TTTTTT                T',
    'T   TT                    TTT            TTTT      TTTTTT         T                                      TTTTH       TTTTTTTTTTTTTTTTTTTT TTTTTT                T',
    'T                                                                 T                                         T__    S                      TTTTTT        K       T',                    
    'TvvvvvvvvTTTTTTTTTvvvTTvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvT       TTTTTTTTTTTTTTTTTTTTTTTT             TvvvvvvTTTTT  TTTTTTTTTTT  TTTTTTTTT       TTT      T',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT H o o o o            TTvvvvvvvvvvvvTTTTTTTTTTTTTTT  L  o  o    o  o   L    TTTTTTTTTT  T', 
    'T  T    T                                                               TTTTTTTTTTTTTTTTTTTT  TTTTTTTTTTTTTTTTTTTTTTTTTTTT   TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT_ T',  
    'TD l    TS                                                                                    T                             T                                   T',  	
    'TTTTT                                                                __________________________                            T    H                               T',   	
    'T    TT                                                        ___                                                 TTTTTTTT     ~       _                      _T',  
    'T                                                                                                               S T                            _                T',  
    'T P       M              ___          >#<            ______                                                      TTS    K                ooS         oo         T',  
    'TTTTTTTTTTTTTTTTTTTS           ____    ^    ___                ___                                              TTT _________     __     __          __      ___T',  
    'T                                                                    TTTTTTTTTTTTTTTTS    ______      __       TTTT          _                                  T',  
    'TvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvTTTTTTvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
 ];

 var boss_level_1 = [
   '#                        ##############    ',
   '#                        #            #    ',
   '#                        #            #    ',
   '#                        #             #   ',
   '#                        #              #  ',
   '#                  R     #               # ',
   '#     ~     ~     ~      #                #',
   '#                        #                #',
   '#                        L   D    M    P  #',
   '###########################################',
   '###########################################',
   '#                                         #',
];

var level_5 = [
   '#                #WW#                               ooo                #                                                                                  WW          #',
   '#                 WW                                                   #                                                                                  WW          #',
   '#                 WW                    oo           v      oo         #                                                                                  WW        P #',
   '# o o o o o       WW        oo          __          >#<     __         #                                                                             oo   WW   #__#####',
   '##############    WW        __                      >#<                #       ###                                                                   ~    WW   #WW#   ',
   '#             #WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#WWWWWWWWWWWWWWWWW#_       #WWWWWWWWWWWWWWWWWWWWWWWWWWW##      o                       o             WW   #WW#   ',
   '#             #WWWjWWWWWWWWWWWWWWW##WWWWWWWWWWWWWWWWW#WWWWWWWWWWWWWW#WW#  o o   #WWWWWWWWWWWWWWWWWWWWWWWWWWW##     >#<   o            o    >#<            WW   #WW#   ',
   '#   _______   #WWWWWWWWWWWWWWWWWSWWWWWWWWWWWWWWWWWWWW#WWWWWWWWWWWWWW#WW#EoEo o  #WWW##WWWWWjWWWWWWWWWWWWWWW###     >#<  >#<    o     >#<   >#<            WW   #WW#   ',
   '#WWWWWWWWWWWWW#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWS#######WWWWWWWWWWW#WW##########WWW##WWWWWWWWWWWWWWWWWWWW####     >#<  >#<   >#<    >#<   >#<   ##       WW   #WW#   ',
   '#WWWWWWWWWWWWW#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW###########WWWWWWWWW#WWWWWWWWWWWWWWWWWWSWWWWWWWWWWW###########vvvvvv#vvvv#vvvvv#vvvvvv#vvvvv#vvvv##WWWWWWWWWWWW#WW#   ',
   '######WWWW#####__WWWW__#########################################################################################################################################WW#', 
   '#    #WWWW#      WWWW         #  #                                                                                                                 >##<        #WW#',
   '#    #WWWW#      WWWW         #  #                                   oo                                                                            >##<    k   #WW#',
   '# oHo#WWWW#    o WWWW o       #  #                                o      o                                                                          ^^     ~   #WW#',
   '# ___#WWWW#    __WWWW__       #  #                S                  vv                                                     vv       S   vv                    #WW#',
   '#    #WWWW# o    WWWW       o #  #                           ooo    >##<    ooo   o         o                       oo     >##<    oo   >##<    ~       ~      #WW#',   
   '#oo  #WWWW#__    WWjW       __#  #                    oo    >###<   >##<   >###<  ##E      ##      oo              ####    >##<    ~    >##<    oo      oo     #WW#',   
   '#__  #WWWW#WWWWWWWWWWWWWWWWWWW#  #                   >##<    ^^^     ^^     ^^^    #########       ~         ##             ^^           ^^     ~       ~      #WW#',
   '#    #WWWW##WWWWWWWWWWWWWWWWWW#oo#      ___           ^^                           #       #                 ##vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#WW#', 
   '#  oo#WWWW###WWWWWWWWWWWWWWWWWlool             _#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#       #vvvvvvvvvvvvvvvvv###################################################WW#',  
   '#  __#WWWW###########################WWWWWWWWWWW###############################################################                                                #WW#',  
   '#     WWWW                 #WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW###   ##WWWWWWWWWWW#                                                                     #WW#',  
   '#oo   WWWW                ##WWWWWWWWWWWWW##WWWWWWWWWWWWWWWWWWWWWWWWWWW###ooo##WWWWWWWWWWW#                                                                     #WW#',  
   '#__   WWWW                 WWWWWWWWWWWWWW##WWWWWWWWWWWWWWWWWWWWWWWWWWWWW#ooo##WWW#_____WW#                                                                     #WW#',  
   '#     WWWW            M    WWWWjWWWWWWWWWWWWWWWWWW##WWWWWWWWWWWWWWWWWWWWWWWWWWWWW#     WW#                 o   o   o   o   o           oo      S            k  #WW#',  
   '#     WWWW         #########WWWWWWWWWWWWWWWWWWWWWW##WWWWjWWWWWWWWWWWWWWWWWWWWWWW## oo  WW# o  o  o  o  #WWW###################         ~         oo         ~  #WW#',  
   '#     WWWW         #       #WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW###########  __  WW#             #WWW#     #WWWWWWWWWWWW                   ~             #WW#',  
   '#WWSWWWWWWWWWWWWWW##       #WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW##WWWW#                WW#E      E     #WjW#    ##WWWWWWWWWWWW S        oo     vvvvvvvvvvvvvvvv#WW#',  
   '#WWWWWWWWWWWWWWWWW##  D K  #WWWWWWWWWWWWWWWWWWWWWWWWWWW##WWWWWWW##WWWW#  o o o o o o  #WW###############WWW######WWW########WW          ~      #################WW#',  
   '#WWWWWWWWWWWWWWWSW##  ###  #WW##WWWWWWWWW##WWWWWWWWWWWW##WWWWWWWWWWWWW#S              #WWWWWWWWWWWWSWWWWWWWWWWWWWWWW#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#',  
   ' ###################       LWW##WWWWWWWWW##WWWWWWWWWWWWWWWWWWWWWWWWWWW#################WWWWWWWWWWWWWWWWWWWWWWWWWWWWW##WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#',   
   '                      ##########vvvvvvvvv##vvvvvvvvvvvvvvvvvvvvvvvvvvv#############################################################################################',  
   '###################################################################################################################################################################',  
];

var level_6 = [
   '######################                                                                                       ######################   ',
   '#   #            # # #                                                                                         WWWWWWWWWWWWW# ooo #   ',
   '#   #            # # #                                                                                         WWWWWWWWWWjWW# oKo #   ',
   '# D l   P    M   L L L                                                                                       ####WWWWWWWWWWW# ooo #   ',
   '#######################                                                                                         #WWWWWWWWWWW##WWWW#   ',
   '#                    ###                                               #####  S     TT                          #WWWWWWjWWWWWWWWWW#   ',
   '#                    ####                                             ######                                    ##WWWWWWWWWWWWWjW##   ',
   '#                    #####                                           #######        S     TT                    #WWWWWWWWWWjWWWWWW#   ',
   '#                    ######                                         ########                                   o#WWWWWWWWWWWWWWWWW#   ',
   '#           o      o ##########################################  ###########vvvvvvvvv                oo        o#WWWWWW###############',
   '##############WWWW####                                             o o o ###^^^^^^^^^                ~          #WWWjWWWWWWWWWWWWW oo#',
   '##############WWWW#                 ######################################<                                     ##WWWWWWWWWWWWWWWW oo#',
   '#WWWWWWW#    #WWWW#                #    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#<                                   ~ #WWWWWWWSWWWWWW#######',
   '#jWWWWjW######WWWW#               #  k  WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#<                 oo       TT         #WWWWWWWWWWWWWWWWW#',
   '#WWW#WWWWWWWWWWWWW#                ###################################WWj#<  S      TT      TT                  ###WWWWWWWWWWWWWWW#',
   '#WWW#WWWWWWWWWWWWW#        oo                                         #WW#<         S                           #WWWWWWWWWWWWWWWWW#',
   '#WWW###############        ~                                          #WW#<                    S                #WWWWWWWW#oo#WWWWW#',
   '#WWW#####WWWWWWWW##  oo                                               #WW#<   TT                                #WWWWWWWWW##WWWWjW#',
   '#WWjWWWWWWWWWWWWW##  ~         o  o  o  o      o      o      o        #WW#<                 oo      oo        K #WWWWWWWWWWWWWWWWW#',
   '#WWWWWWWWWWW#WWWW##                            #E     #E     #E       #WW#<         TT      TT      TT       TTT#WWWWWWWWWWWWWWW###',
   '#############WWWW#########################WWWWW#####################  #WW#<vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv#WWWWWWjWWWWWWWWWW#',
   '#           #WWWW#         #             #WWWjW#                      #WW##########################################WWWWWWWWWWWWWWW#',
   '#           #WWWW#         #             ##WWWW# K  o  o   o  o       #WW#     #WW#  #WW#                    #oo WWWWWWWWWWWWWWWWW#',
   '#           #    #         #             #WWWWW#                     ##WW##    #jW#  #Wj# H o o o o o o o    #oo WWWWWWWWWWWWWWWWW#',
   '#                        #################WWWWW#########o o############WW#######WW####WW###########   #############WWWWWWWWWWWWWWW#',
   '#                         WWWWWWWWWWWWWWWWWWWW#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#',
   '#          o o o o        WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW###',
   '#                         WWWWWWWWWWWWWWWWWjWWWWWWWWWWWWWWWWWWWWWWWWWWWjWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#',
   '#  o o o  ##########     #######################################################Wj####jW#############################WWWWWWWWWWWWW#',
   '#         #        #       #                                                   #WW#  #WW# o  o  o  o  o  o  o  o     WWWWWWWWWWWWW#',
   '##################################################################################################################################W',
];
 
 var town = [
    '#                                               r                                                                       #',
    '#                                               r                                                                       #',
    '#                                               r                                                                       #',
    '#                                               r                                                                       #',
    '#                                               r                                                                       #',
    '#                                               r                #                                                      #',
    '#                                               r   ##WWWWWWWWWWW##                                                     #',
    '#     $                          5     h        r  ###WWWWWjWWWWW###    d                                               #',
    '# M            1   2   3   4   #####          Y r ####WWWWWWWWWWW####         6   7   8                                 #',
    '#######################################################WWWWWWWWWW########################################################', 
    '#########################################################################################################################',    
    '#                                                                                                                       #',   
    '#                                                           #WW#           #WWWWWWWWWWWW                                #',  
    '#                                                            WW            #WWWWWWW###WW                                #', 
    '#                                                            WW            #WWWWWWWW# WW                                #', 
    '#                                                            WW            ###WWWWWW# WW  __                            #', 
    '#                                                          WWWWWW          #WWWWWWWW# WW                                #', 
    '#                                                  WWWWWWWWWWWWWWWWWWWWWW  #WWWWWW### WW                                #', 
    '#                                        #WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#WWWWWWW##                          #', 
    '#                                       ##WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW#WWWWWWW###                         #', 
    '#########################################################################################################################',
 ];

 var levels = [town, level_1, level_2, level_3, level_4, boss_level_1, level_5, level_6];

function loadImages() 
{
   
   images = {};
   var imgs = [
      "player_blink", "block", "coin", "diamond", "heart", "background", "enemies", "portal", "boss_portal", "lock", "lock_silver", "key", "key_silver", "spikes", "platform", "falling_platform" , "enemy_spike", "armor",
      "BigRed", "BigRed_Attack", "block_bigred", "Miner", "jellyfish", "Mayor", "talk", "chat", "shop_vendor", "shop_dialogs", "diamond_shop", "diamond_dialogs", "diamond_icon", "donate_shop"
   ];

   for(var img in imgs) {
      var image = new Image(); img = imgs[img];
      image.src = "imgs/" + img + ".png";
      images[img] = image
   }
   
   return images;
}

var images = loadImages();